#!/bin/sh
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan view:clear
php artisan optimize
composer clearcache
composer dumpautoload -o
printf 'all DONE \360\237\230\216\n'
